# Generated by Django 3.1.2 on 2021-01-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djaxifyapp', '0002_auto_20210125_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
