# Generated by Django 3.1.2 on 2021-01-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djaxifyapp', '0003_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
