# Generated by Django 3.1.2 on 2021-03-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djaxifyapp', '0004_post_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
